/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Spatialbicycle_model_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {6, 1, 1};
static const casadi_int casadi_s1[3] = {2, 1, 1};
static const casadi_int casadi_s2[3] = {1, 1, 1};
static const casadi_int casadi_s3[11] = 
  {8, 1, 0, 7, 1, 2, 3, 4,
  5, 6, 7};

/* Spatialbicycle_model_expl_vde_adj:(i0[6],i1[6],i2[2],i3)->(o0[8x1,7nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w00, w01, w02, w03, w04, w05, w06, w07, w08, w09, *w10=w+10, w11;
  casadi_real w12, w13, w14, w15, w16, w17, w18, w19, w20, w21, w22, w23;
  /* #0: @0 = input[3][0] */
  w00 = arg[3] ? arg[3][0] : 0;
  /* #1: @1 = input[0][3] */
  w01 = arg[0] ? arg[0][3] : 0;
  /* #2: @2 = input[0][2] */
  w02 = arg[0] ? arg[0][2] : 0;
  /* #3: @3 = 0.5 */
  w03 = 5.0000000000000000e-01;
  /* #4: @4 = input[0][5] */
  w04 = arg[0] ? arg[0][5] : 0;
  /* #5: @5 = (@3*@4) */
  w05  = (w03*w04);
  /* #6: @2 = (@2+@5) */
  w02 += w05;
  /* #7: @6 = cos(@2) */
  w06 = cos( w02 );
  /* #8: @7 = (@1*@6) */
  w07  = (w01*w06);
  /* #9: @8 = 1 */
  w08 = 1.;
  /* #10: @9 = input[0][1] */
  w09 = arg[0] ? arg[0][1] : 0;
  /* #11: @9 = (@0*@9) */
  w09  = (w00*w09);
  /* #12: @9 = (@8-@9) */
  w09  = (w08-w09);
  /* #13: @7 = (@7/@9) */
  w07 /= w09;
  /* #14: @7 = (@7/@9) */
  w07 /= w09;
  /* #15: @10 = input[1][0] */
  casadi_copy(arg[1], 6, w10);
  /* #16: {@11, @12, @13, @14, @15, @16} = vertsplit(@10) */
  w11 = w10[0];
  w12 = w10[1];
  w13 = w10[2];
  w14 = w10[3];
  w15 = w10[4];
  w16 = w10[5];
  /* #17: @17 = (@0*@13) */
  w17  = (w00*w13);
  /* #18: @11 = (@11-@17) */
  w11 -= w17;
  /* #19: @7 = (@7*@11) */
  w07 *= w11;
  /* #20: @0 = (@0*@7) */
  w00 *= w07;
  /* #21: output[0][0] = @0 */
  if (res[0]) res[0][0] = w00;
  /* #22: @0 = (@1*@12) */
  w00  = (w01*w12);
  /* #23: @0 = (@6*@0) */
  w00  = (w06*w00);
  /* #24: @2 = sin(@2) */
  w02 = sin( w02 );
  /* #25: @11 = (@11/@9) */
  w11 /= w09;
  /* #26: @9 = (@1*@11) */
  w09  = (w01*w11);
  /* #27: @9 = (@2*@9) */
  w09  = (w02*w09);
  /* #28: @7 = (@0-@9) */
  w07  = (w00-w09);
  /* #29: output[0][1] = @7 */
  if (res[0]) res[0][1] = w07;
  /* #30: @7 = 0.011 */
  w07 = 1.0999999999999999e-02;
  /* #31: @17 = (@7*@1) */
  w17  = (w07*w01);
  /* #32: @18 = 0.666667 */
  w18 = 6.6666666666666663e-01;
  /* #33: @19 = cos(@5) */
  w19 = cos( w05 );
  /* #34: @19 = (@19*@14) */
  w19 *= w14;
  /* #35: @18 = (@18*@19) */
  w18 *= w19;
  /* #36: @19 = (@17*@18) */
  w19  = (w17*w18);
  /* #37: @19 = (-@19) */
  w19 = (- w19 );
  /* #38: @20 = 5 */
  w20 = 5.;
  /* #39: @21 = (@20*@1) */
  w21  = (w20*w01);
  /* #40: @21 = tanh(@21) */
  w21 = tanh( w21 );
  /* #41: @22 = sq(@21) */
  w22 = casadi_sq( w21 );
  /* #42: @8 = (@8-@22) */
  w08 -= w22;
  /* #43: @22 = 0.006 */
  w22 = 6.0000000000000001e-03;
  /* #44: @23 = (@22*@18) */
  w23  = (w22*w18);
  /* #45: @8 = (@8*@23) */
  w08 *= w23;
  /* #46: @20 = (@20*@8) */
  w20 *= w08;
  /* #47: @19 = (@19-@20) */
  w19 -= w20;
  /* #48: @20 = (@1*@18) */
  w20  = (w01*w18);
  /* #49: @7 = (@7*@20) */
  w07 *= w20;
  /* #50: @19 = (@19-@7) */
  w19 -= w07;
  /* #51: @7 = 0.05 */
  w07 = 5.0000000000000003e-02;
  /* #52: @20 = input[0][4] */
  w20 = arg[0] ? arg[0][4] : 0;
  /* #53: @8 = (@20*@18) */
  w08  = (w20*w18);
  /* #54: @8 = (@7*@8) */
  w08  = (w07*w08);
  /* #55: @19 = (@19-@8) */
  w19 -= w08;
  /* #56: @8 = 15.5 */
  w08 = 1.5500000000000000e+01;
  /* #57: @4 = (@4*@13) */
  w04 *= w13;
  /* #58: @4 = (@8*@4) */
  w04  = (w08*w04);
  /* #59: @19 = (@19+@4) */
  w19 += w04;
  /* #60: @2 = (@2*@12) */
  w02 *= w12;
  /* #61: @19 = (@19+@2) */
  w19 += w02;
  /* #62: @6 = (@6*@11) */
  w06 *= w11;
  /* #63: @19 = (@19+@6) */
  w19 += w06;
  /* #64: output[0][2] = @19 */
  if (res[0]) res[0][2] = w19;
  /* #65: @19 = 0.28 */
  w19 = 2.8000000000000003e-01;
  /* #66: @7 = (@7*@1) */
  w07 *= w01;
  /* #67: @19 = (@19-@7) */
  w19 -= w07;
  /* #68: @18 = (@19*@18) */
  w18  = (w19*w18);
  /* #69: output[0][3] = @18 */
  if (res[0]) res[0][3] = w18;
  /* #70: @8 = (@8*@1) */
  w08 *= w01;
  /* #71: @8 = (@8*@13) */
  w08 *= w13;
  /* #72: @5 = sin(@5) */
  w05 = sin( w05 );
  /* #73: @19 = (@19*@20) */
  w19 *= w20;
  /* #74: @17 = (@17*@1) */
  w17 *= w01;
  /* #75: @19 = (@19-@17) */
  w19 -= w17;
  /* #76: @22 = (@22*@21) */
  w22 *= w21;
  /* #77: @19 = (@19-@22) */
  w19 -= w22;
  /* #78: @22 = 1.5 */
  w22 = 1.5000000000000000e+00;
  /* #79: @19 = (@19/@22) */
  w19 /= w22;
  /* #80: @19 = (@19*@14) */
  w19 *= w14;
  /* #81: @5 = (@5*@19) */
  w05 *= w19;
  /* #82: @5 = (@3*@5) */
  w05  = (w03*w05);
  /* #83: @8 = (@8-@5) */
  w08 -= w05;
  /* #84: @0 = (@3*@0) */
  w00  = (w03*w00);
  /* #85: @8 = (@8+@0) */
  w08 += w00;
  /* #86: @3 = (@3*@9) */
  w03 *= w09;
  /* #87: @8 = (@8-@3) */
  w08 -= w03;
  /* #88: output[0][4] = @8 */
  if (res[0]) res[0][4] = w08;
  /* #89: output[0][5] = @15 */
  if (res[0]) res[0][5] = w15;
  /* #90: output[0][6] = @16 */
  if (res[0]) res[0][6] = w16;
  return 0;
}

CASADI_SYMBOL_EXPORT int Spatialbicycle_model_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Spatialbicycle_model_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Spatialbicycle_model_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Spatialbicycle_model_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Spatialbicycle_model_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Spatialbicycle_model_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Spatialbicycle_model_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void Spatialbicycle_model_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Spatialbicycle_model_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int Spatialbicycle_model_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real Spatialbicycle_model_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Spatialbicycle_model_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Spatialbicycle_model_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Spatialbicycle_model_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Spatialbicycle_model_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Spatialbicycle_model_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 7;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 29;
  return 0;
}

CASADI_SYMBOL_EXPORT int Spatialbicycle_model_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 7*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 29*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
