/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Spatialbicycle_model_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[3] = {6, 1, 1};
static const casadi_int casadi_s1[3] = {2, 1, 1};
static const casadi_int casadi_s2[3] = {1, 1, 1};

/* Spatialbicycle_model_expl_ode_fun:(i0[6],i1[2],i2)->(o0[6]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1, w2, w3, w4, w5, w6, w7;
  /* #0: @0 = input[0][3] */
  w0 = arg[0] ? arg[0][3] : 0;
  /* #1: @1 = input[0][2] */
  w1 = arg[0] ? arg[0][2] : 0;
  /* #2: @2 = 0.5 */
  w2 = 5.0000000000000000e-01;
  /* #3: @3 = input[0][5] */
  w3 = arg[0] ? arg[0][5] : 0;
  /* #4: @2 = (@2*@3) */
  w2 *= w3;
  /* #5: @1 = (@1+@2) */
  w1 += w2;
  /* #6: @4 = cos(@1) */
  w4 = cos( w1 );
  /* #7: @4 = (@0*@4) */
  w4  = (w0*w4);
  /* #8: @5 = 1 */
  w5 = 1.;
  /* #9: @6 = input[2][0] */
  w6 = arg[2] ? arg[2][0] : 0;
  /* #10: @7 = input[0][1] */
  w7 = arg[0] ? arg[0][1] : 0;
  /* #11: @7 = (@6*@7) */
  w7  = (w6*w7);
  /* #12: @5 = (@5-@7) */
  w5 -= w7;
  /* #13: @4 = (@4/@5) */
  w4 /= w5;
  /* #14: output[0][0] = @4 */
  if (res[0]) res[0][0] = w4;
  /* #15: @1 = sin(@1) */
  w1 = sin( w1 );
  /* #16: @1 = (@0*@1) */
  w1  = (w0*w1);
  /* #17: output[0][1] = @1 */
  if (res[0]) res[0][1] = w1;
  /* #18: @1 = 15.5 */
  w1 = 1.5500000000000000e+01;
  /* #19: @1 = (@1*@0) */
  w1 *= w0;
  /* #20: @1 = (@1*@3) */
  w1 *= w3;
  /* #21: @6 = (@6*@4) */
  w6 *= w4;
  /* #22: @1 = (@1-@6) */
  w1 -= w6;
  /* #23: output[0][2] = @1 */
  if (res[0]) res[0][2] = w1;
  /* #24: @1 = 0.28 */
  w1 = 2.8000000000000003e-01;
  /* #25: @6 = 0.05 */
  w6 = 5.0000000000000003e-02;
  /* #26: @6 = (@6*@0) */
  w6 *= w0;
  /* #27: @1 = (@1-@6) */
  w1 -= w6;
  /* #28: @6 = input[0][4] */
  w6 = arg[0] ? arg[0][4] : 0;
  /* #29: @1 = (@1*@6) */
  w1 *= w6;
  /* #30: @6 = 0.011 */
  w6 = 1.0999999999999999e-02;
  /* #31: @6 = (@6*@0) */
  w6 *= w0;
  /* #32: @6 = (@6*@0) */
  w6 *= w0;
  /* #33: @1 = (@1-@6) */
  w1 -= w6;
  /* #34: @6 = 0.006 */
  w6 = 6.0000000000000001e-03;
  /* #35: @4 = 5 */
  w4 = 5.;
  /* #36: @4 = (@4*@0) */
  w4 *= w0;
  /* #37: @4 = tanh(@4) */
  w4 = tanh( w4 );
  /* #38: @6 = (@6*@4) */
  w6 *= w4;
  /* #39: @1 = (@1-@6) */
  w1 -= w6;
  /* #40: @6 = 1.5 */
  w6 = 1.5000000000000000e+00;
  /* #41: @1 = (@1/@6) */
  w1 /= w6;
  /* #42: @2 = cos(@2) */
  w2 = cos( w2 );
  /* #43: @1 = (@1*@2) */
  w1 *= w2;
  /* #44: output[0][3] = @1 */
  if (res[0]) res[0][3] = w1;
  /* #45: @1 = input[1][0] */
  w1 = arg[1] ? arg[1][0] : 0;
  /* #46: output[0][4] = @1 */
  if (res[0]) res[0][4] = w1;
  /* #47: @1 = input[1][1] */
  w1 = arg[1] ? arg[1][1] : 0;
  /* #48: output[0][5] = @1 */
  if (res[0]) res[0][5] = w1;
  return 0;
}

CASADI_SYMBOL_EXPORT int Spatialbicycle_model_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Spatialbicycle_model_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Spatialbicycle_model_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Spatialbicycle_model_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Spatialbicycle_model_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Spatialbicycle_model_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Spatialbicycle_model_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void Spatialbicycle_model_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Spatialbicycle_model_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int Spatialbicycle_model_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real Spatialbicycle_model_expl_ode_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Spatialbicycle_model_expl_ode_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Spatialbicycle_model_expl_ode_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Spatialbicycle_model_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Spatialbicycle_model_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Spatialbicycle_model_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 8;
  return 0;
}

CASADI_SYMBOL_EXPORT int Spatialbicycle_model_expl_ode_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 8*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
