/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Spatialbicycle_model_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_project CASADI_PREFIX(project)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_trans CASADI_PREFIX(trans)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

void casadi_project(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, const casadi_int* sp_y, casadi_real* w) {
  casadi_int ncol_x, ncol_y, i, el;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  for (i=0; i<ncol_x; ++i) {
    for (el=colind_y[i]; el<colind_y[i+1]; ++el) w[row_y[el]] = 0;
    for (el=colind_x[i]; el<colind_x[i+1]; ++el) w[row_x[el]] = x[el];
    for (el=colind_y[i]; el<colind_y[i+1]; ++el) y[el] = w[row_y[el]];
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[7] = {6, 2, 0, 1, 2, 4, 5};
static const casadi_int casadi_s1[11] = 
  {2, 6, 0, 0, 0, 0, 0, 1,
  2, 0, 1};
static const casadi_int casadi_s2[15] = 
  {6, 2, 0, 5, 10, 0, 1, 2,
  3, 4, 0, 1, 2, 3, 5};
static const casadi_int casadi_s3[13] = 
  {6, 2, 0, 4, 8, 0, 1, 2,
  3, 0, 1, 2, 3};
static const casadi_int casadi_s4[3] = {6, 1, 1};
static const casadi_int casadi_s5[3] = {6, 6, 1};
static const casadi_int casadi_s6[3] = {6, 2, 1};
static const casadi_int casadi_s7[3] = {2, 1, 1};
static const casadi_int casadi_s8[3] = {1, 1, 1};
static const casadi_int casadi_s9[33] = 
  {6, 6, 0, 4, 8, 12, 16, 20,
  24, 0, 1, 2, 3, 0, 1, 2,
  3, 0, 1, 2, 3, 0, 1, 2,
  3, 0, 1, 2, 3, 0, 1, 2,
  3};

static const casadi_real casadi_zeros[36] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0.};

/* Spatialbicycle_model_expl_vde_forw:(i0[6],i1[6x6],i2[6x2],i3[2],i4)->(o0[6],o1[6x6,24nz],o2[6x2,10nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, w00, w01, w02, w03, w04, w05, w06, w07, w08, w09, w10;
  casadi_real w11, w12, w13, w14, w15, w16, w17, w18, w19, w20, w21, w22;
  casadi_real w30, w31, w32, w33, w34, w35, w36, *w37=w+108, *w39=w+110, *w40=w+112, *w41=w+114, *w43=w+136;
  casadi_real *w44=w+140, *w45=w+144, *w46=w+152;
  const casadi_real *cs, *wr23, *wr24, *wr25, *wr26, *wr27, *wr28, *wr29, *wr42;
  /* #0: @0 = input[0][3] */
  w00 = arg[0] ? arg[0][3] : 0;
  /* #1: @1 = input[0][2] */
  w01 = arg[0] ? arg[0][2] : 0;
  /* #2: @2 = 0.5 */
  w02 = 5.0000000000000000e-01;
  /* #3: @3 = input[0][5] */
  w03 = arg[0] ? arg[0][5] : 0;
  /* #4: @4 = (@2*@3) */
  w04  = (w02*w03);
  /* #5: @1 = (@1+@4) */
  w01 += w04;
  /* #6: @5 = cos(@1) */
  w05 = cos( w01 );
  /* #7: @6 = (@0*@5) */
  w06  = (w00*w05);
  /* #8: @7 = 1 */
  w07 = 1.;
  /* #9: @8 = input[4][0] */
  w08 = arg[4] ? arg[4][0] : 0;
  /* #10: @9 = input[0][1] */
  w09 = arg[0] ? arg[0][1] : 0;
  /* #11: @9 = (@8*@9) */
  w09  = (w08*w09);
  /* #12: @9 = (@7-@9) */
  w09  = (w07-w09);
  /* #13: @6 = (@6/@9) */
  w06 /= w09;
  /* #14: output[0][0] = @6 */
  if (res[0]) res[0][0] = w06;
  /* #15: @1 = sin(@1) */
  w01 = sin( w01 );
  /* #16: @10 = (@0*@1) */
  w10  = (w00*w01);
  /* #17: output[0][1] = @10 */
  if (res[0]) res[0][1] = w10;
  /* #18: @10 = 15.5 */
  w10 = 1.5500000000000000e+01;
  /* #19: @11 = (@10*@0) */
  w11  = (w10*w00);
  /* #20: @12 = (@11*@3) */
  w12  = (w11*w03);
  /* #21: @13 = (@8*@6) */
  w13  = (w08*w06);
  /* #22: @12 = (@12-@13) */
  w12 -= w13;
  /* #23: output[0][2] = @12 */
  if (res[0]) res[0][2] = w12;
  /* #24: @12 = 0.28 */
  w12 = 2.8000000000000003e-01;
  /* #25: @13 = 0.05 */
  w13 = 5.0000000000000003e-02;
  /* #26: @14 = (@13*@0) */
  w14  = (w13*w00);
  /* #27: @12 = (@12-@14) */
  w12 -= w14;
  /* #28: @14 = input[0][4] */
  w14 = arg[0] ? arg[0][4] : 0;
  /* #29: @15 = (@12*@14) */
  w15  = (w12*w14);
  /* #30: @16 = 0.006 */
  w16 = 6.0000000000000001e-03;
  /* #31: @17 = (@16*@0) */
  w17  = (w16*w00);
  /* #32: @18 = (@17*@0) */
  w18  = (w17*w00);
  /* #33: @15 = (@15-@18) */
  w15 -= w18;
  /* #34: @18 = 0.011 */
  w18 = 1.0999999999999999e-02;
  /* #35: @19 = 5 */
  w19 = 5.;
  /* #36: @20 = (@19*@0) */
  w20  = (w19*w00);
  /* #37: @20 = tanh(@20) */
  w20 = tanh( w20 );
  /* #38: @21 = (@18*@20) */
  w21  = (w18*w20);
  /* #39: @15 = (@15-@21) */
  w15 -= w21;
  /* #40: @21 = 0.043 */
  w21 = 4.2999999999999997e-02;
  /* #41: @15 = (@15/@21) */
  w15 /= w21;
  /* #42: @21 = cos(@4) */
  w21 = cos( w04 );
  /* #43: @22 = (@15*@21) */
  w22  = (w15*w21);
  /* #44: output[0][3] = @22 */
  if (res[0]) res[0][3] = w22;
  /* #45: @22 = input[3][0] */
  w22 = arg[3] ? arg[3][0] : 0;
  /* #46: output[0][4] = @22 */
  if (res[0]) res[0][4] = w22;
  /* #47: @22 = input[3][1] */
  w22 = arg[3] ? arg[3][1] : 0;
  /* #48: output[0][5] = @22 */
  if (res[0]) res[0][5] = w22;
  /* #49: @23 = input[1][0] */
  wr23 = arg[1] ? arg[1] : casadi_zeros;
  /* #50: {@24, @25, @26, @27, @28, @29} = horzsplit(@23) */
  wr24 = wr23;
  wr25 = wr23+6;
  wr26 = wr23+12;
  wr27 = wr23+18;
  wr28 = wr23+24;
  wr29 = wr23+30;
  /* #51: {NULL, @22, @30, @31, @32, @33} = vertsplit(@24) */
  w22 = wr24[1];
  w30 = wr24[2];
  w31 = wr24[3];
  w32 = wr24[4];
  w33 = wr24[5];
  /* #52: @34 = (@5*@31) */
  w34  = (w05*w31);
  /* #53: @35 = (@2*@33) */
  w35  = (w02*w33);
  /* #54: @30 = (@30+@35) */
  w30 += w35;
  /* #55: @36 = (@1*@30) */
  w36  = (w01*w30);
  /* #56: @36 = (@0*@36) */
  w36  = (w00*w36);
  /* #57: @34 = (@34-@36) */
  w34 -= w36;
  /* #58: @34 = (@34/@9) */
  w34 /= w09;
  /* #59: @6 = (@6/@9) */
  w06 /= w09;
  /* #60: @22 = (@8*@22) */
  w22  = (w08*w22);
  /* #61: @22 = (@6*@22) */
  w22  = (w06*w22);
  /* #62: @34 = (@34+@22) */
  w34 += w22;
  /* #63: output[1][0] = @34 */
  if (res[1]) res[1][0] = w34;
  /* #64: @22 = (@1*@31) */
  w22  = (w01*w31);
  /* #65: @30 = (@5*@30) */
  w30  = (w05*w30);
  /* #66: @30 = (@0*@30) */
  w30  = (w00*w30);
  /* #67: @22 = (@22+@30) */
  w22 += w30;
  /* #68: output[1][1] = @22 */
  if (res[1]) res[1][1] = w22;
  /* #69: @22 = (@10*@31) */
  w22  = (w10*w31);
  /* #70: @22 = (@3*@22) */
  w22  = (w03*w22);
  /* #71: @33 = (@11*@33) */
  w33  = (w11*w33);
  /* #72: @22 = (@22+@33) */
  w22 += w33;
  /* #73: @34 = (@8*@34) */
  w34  = (w08*w34);
  /* #74: @22 = (@22-@34) */
  w22 -= w34;
  /* #75: output[1][2] = @22 */
  if (res[1]) res[1][2] = w22;
  /* #76: @22 = 23.2558 */
  w22 = 2.3255813953488374e+01;
  /* #77: @32 = (@12*@32) */
  w32  = (w12*w32);
  /* #78: @34 = (@13*@31) */
  w34  = (w13*w31);
  /* #79: @34 = (@14*@34) */
  w34  = (w14*w34);
  /* #80: @32 = (@32-@34) */
  w32 -= w34;
  /* #81: @34 = (@16*@31) */
  w34  = (w16*w31);
  /* #82: @34 = (@0*@34) */
  w34  = (w00*w34);
  /* #83: @33 = (@17*@31) */
  w33  = (w17*w31);
  /* #84: @34 = (@34+@33) */
  w34 += w33;
  /* #85: @32 = (@32-@34) */
  w32 -= w34;
  /* #86: @20 = sq(@20) */
  w20 = casadi_sq( w20 );
  /* #87: @7 = (@7-@20) */
  w07 -= w20;
  /* #88: @31 = (@19*@31) */
  w31  = (w19*w31);
  /* #89: @31 = (@7*@31) */
  w31  = (w07*w31);
  /* #90: @31 = (@18*@31) */
  w31  = (w18*w31);
  /* #91: @32 = (@32-@31) */
  w32 -= w31;
  /* #92: @32 = (@22*@32) */
  w32  = (w22*w32);
  /* #93: @32 = (@21*@32) */
  w32  = (w21*w32);
  /* #94: @4 = sin(@4) */
  w04 = sin( w04 );
  /* #95: @35 = (@4*@35) */
  w35  = (w04*w35);
  /* #96: @35 = (@15*@35) */
  w35  = (w15*w35);
  /* #97: @32 = (@32-@35) */
  w32 -= w35;
  /* #98: output[1][3] = @32 */
  if (res[1]) res[1][3] = w32;
  /* #99: {NULL, @32, @35, @31, @20, @34} = vertsplit(@25) */
  w32 = wr25[1];
  w35 = wr25[2];
  w31 = wr25[3];
  w20 = wr25[4];
  w34 = wr25[5];
  /* #100: @33 = (@5*@31) */
  w33  = (w05*w31);
  /* #101: @30 = (@2*@34) */
  w30  = (w02*w34);
  /* #102: @35 = (@35+@30) */
  w35 += w30;
  /* #103: @36 = (@1*@35) */
  w36  = (w01*w35);
  /* #104: @36 = (@0*@36) */
  w36  = (w00*w36);
  /* #105: @33 = (@33-@36) */
  w33 -= w36;
  /* #106: @33 = (@33/@9) */
  w33 /= w09;
  /* #107: @32 = (@8*@32) */
  w32  = (w08*w32);
  /* #108: @32 = (@6*@32) */
  w32  = (w06*w32);
  /* #109: @33 = (@33+@32) */
  w33 += w32;
  /* #110: output[1][4] = @33 */
  if (res[1]) res[1][4] = w33;
  /* #111: @32 = (@1*@31) */
  w32  = (w01*w31);
  /* #112: @35 = (@5*@35) */
  w35  = (w05*w35);
  /* #113: @35 = (@0*@35) */
  w35  = (w00*w35);
  /* #114: @32 = (@32+@35) */
  w32 += w35;
  /* #115: output[1][5] = @32 */
  if (res[1]) res[1][5] = w32;
  /* #116: @32 = (@10*@31) */
  w32  = (w10*w31);
  /* #117: @32 = (@3*@32) */
  w32  = (w03*w32);
  /* #118: @34 = (@11*@34) */
  w34  = (w11*w34);
  /* #119: @32 = (@32+@34) */
  w32 += w34;
  /* #120: @33 = (@8*@33) */
  w33  = (w08*w33);
  /* #121: @32 = (@32-@33) */
  w32 -= w33;
  /* #122: output[1][6] = @32 */
  if (res[1]) res[1][6] = w32;
  /* #123: @20 = (@12*@20) */
  w20  = (w12*w20);
  /* #124: @32 = (@13*@31) */
  w32  = (w13*w31);
  /* #125: @32 = (@14*@32) */
  w32  = (w14*w32);
  /* #126: @20 = (@20-@32) */
  w20 -= w32;
  /* #127: @32 = (@16*@31) */
  w32  = (w16*w31);
  /* #128: @32 = (@0*@32) */
  w32  = (w00*w32);
  /* #129: @33 = (@17*@31) */
  w33  = (w17*w31);
  /* #130: @32 = (@32+@33) */
  w32 += w33;
  /* #131: @20 = (@20-@32) */
  w20 -= w32;
  /* #132: @31 = (@19*@31) */
  w31  = (w19*w31);
  /* #133: @31 = (@7*@31) */
  w31  = (w07*w31);
  /* #134: @31 = (@18*@31) */
  w31  = (w18*w31);
  /* #135: @20 = (@20-@31) */
  w20 -= w31;
  /* #136: @20 = (@22*@20) */
  w20  = (w22*w20);
  /* #137: @20 = (@21*@20) */
  w20  = (w21*w20);
  /* #138: @30 = (@4*@30) */
  w30  = (w04*w30);
  /* #139: @30 = (@15*@30) */
  w30  = (w15*w30);
  /* #140: @20 = (@20-@30) */
  w20 -= w30;
  /* #141: output[1][7] = @20 */
  if (res[1]) res[1][7] = w20;
  /* #142: {NULL, @20, @30, @31, @32, @33} = vertsplit(@26) */
  w20 = wr26[1];
  w30 = wr26[2];
  w31 = wr26[3];
  w32 = wr26[4];
  w33 = wr26[5];
  /* #143: @34 = (@5*@31) */
  w34  = (w05*w31);
  /* #144: @35 = (@2*@33) */
  w35  = (w02*w33);
  /* #145: @30 = (@30+@35) */
  w30 += w35;
  /* #146: @36 = (@1*@30) */
  w36  = (w01*w30);
  /* #147: @36 = (@0*@36) */
  w36  = (w00*w36);
  /* #148: @34 = (@34-@36) */
  w34 -= w36;
  /* #149: @34 = (@34/@9) */
  w34 /= w09;
  /* #150: @20 = (@8*@20) */
  w20  = (w08*w20);
  /* #151: @20 = (@6*@20) */
  w20  = (w06*w20);
  /* #152: @34 = (@34+@20) */
  w34 += w20;
  /* #153: output[1][8] = @34 */
  if (res[1]) res[1][8] = w34;
  /* #154: @20 = (@1*@31) */
  w20  = (w01*w31);
  /* #155: @30 = (@5*@30) */
  w30  = (w05*w30);
  /* #156: @30 = (@0*@30) */
  w30  = (w00*w30);
  /* #157: @20 = (@20+@30) */
  w20 += w30;
  /* #158: output[1][9] = @20 */
  if (res[1]) res[1][9] = w20;
  /* #159: @20 = (@10*@31) */
  w20  = (w10*w31);
  /* #160: @20 = (@3*@20) */
  w20  = (w03*w20);
  /* #161: @33 = (@11*@33) */
  w33  = (w11*w33);
  /* #162: @20 = (@20+@33) */
  w20 += w33;
  /* #163: @34 = (@8*@34) */
  w34  = (w08*w34);
  /* #164: @20 = (@20-@34) */
  w20 -= w34;
  /* #165: output[1][10] = @20 */
  if (res[1]) res[1][10] = w20;
  /* #166: @32 = (@12*@32) */
  w32  = (w12*w32);
  /* #167: @20 = (@13*@31) */
  w20  = (w13*w31);
  /* #168: @20 = (@14*@20) */
  w20  = (w14*w20);
  /* #169: @32 = (@32-@20) */
  w32 -= w20;
  /* #170: @20 = (@16*@31) */
  w20  = (w16*w31);
  /* #171: @20 = (@0*@20) */
  w20  = (w00*w20);
  /* #172: @34 = (@17*@31) */
  w34  = (w17*w31);
  /* #173: @20 = (@20+@34) */
  w20 += w34;
  /* #174: @32 = (@32-@20) */
  w32 -= w20;
  /* #175: @31 = (@19*@31) */
  w31  = (w19*w31);
  /* #176: @31 = (@7*@31) */
  w31  = (w07*w31);
  /* #177: @31 = (@18*@31) */
  w31  = (w18*w31);
  /* #178: @32 = (@32-@31) */
  w32 -= w31;
  /* #179: @32 = (@22*@32) */
  w32  = (w22*w32);
  /* #180: @32 = (@21*@32) */
  w32  = (w21*w32);
  /* #181: @35 = (@4*@35) */
  w35  = (w04*w35);
  /* #182: @35 = (@15*@35) */
  w35  = (w15*w35);
  /* #183: @32 = (@32-@35) */
  w32 -= w35;
  /* #184: output[1][11] = @32 */
  if (res[1]) res[1][11] = w32;
  /* #185: {NULL, @32, @35, @31, @20, @34} = vertsplit(@27) */
  w32 = wr27[1];
  w35 = wr27[2];
  w31 = wr27[3];
  w20 = wr27[4];
  w34 = wr27[5];
  /* #186: @33 = (@5*@31) */
  w33  = (w05*w31);
  /* #187: @30 = (@2*@34) */
  w30  = (w02*w34);
  /* #188: @35 = (@35+@30) */
  w35 += w30;
  /* #189: @36 = (@1*@35) */
  w36  = (w01*w35);
  /* #190: @36 = (@0*@36) */
  w36  = (w00*w36);
  /* #191: @33 = (@33-@36) */
  w33 -= w36;
  /* #192: @33 = (@33/@9) */
  w33 /= w09;
  /* #193: @32 = (@8*@32) */
  w32  = (w08*w32);
  /* #194: @32 = (@6*@32) */
  w32  = (w06*w32);
  /* #195: @33 = (@33+@32) */
  w33 += w32;
  /* #196: output[1][12] = @33 */
  if (res[1]) res[1][12] = w33;
  /* #197: @32 = (@1*@31) */
  w32  = (w01*w31);
  /* #198: @35 = (@5*@35) */
  w35  = (w05*w35);
  /* #199: @35 = (@0*@35) */
  w35  = (w00*w35);
  /* #200: @32 = (@32+@35) */
  w32 += w35;
  /* #201: output[1][13] = @32 */
  if (res[1]) res[1][13] = w32;
  /* #202: @32 = (@10*@31) */
  w32  = (w10*w31);
  /* #203: @32 = (@3*@32) */
  w32  = (w03*w32);
  /* #204: @34 = (@11*@34) */
  w34  = (w11*w34);
  /* #205: @32 = (@32+@34) */
  w32 += w34;
  /* #206: @33 = (@8*@33) */
  w33  = (w08*w33);
  /* #207: @32 = (@32-@33) */
  w32 -= w33;
  /* #208: output[1][14] = @32 */
  if (res[1]) res[1][14] = w32;
  /* #209: @20 = (@12*@20) */
  w20  = (w12*w20);
  /* #210: @32 = (@13*@31) */
  w32  = (w13*w31);
  /* #211: @32 = (@14*@32) */
  w32  = (w14*w32);
  /* #212: @20 = (@20-@32) */
  w20 -= w32;
  /* #213: @32 = (@16*@31) */
  w32  = (w16*w31);
  /* #214: @32 = (@0*@32) */
  w32  = (w00*w32);
  /* #215: @33 = (@17*@31) */
  w33  = (w17*w31);
  /* #216: @32 = (@32+@33) */
  w32 += w33;
  /* #217: @20 = (@20-@32) */
  w20 -= w32;
  /* #218: @31 = (@19*@31) */
  w31  = (w19*w31);
  /* #219: @31 = (@7*@31) */
  w31  = (w07*w31);
  /* #220: @31 = (@18*@31) */
  w31  = (w18*w31);
  /* #221: @20 = (@20-@31) */
  w20 -= w31;
  /* #222: @20 = (@22*@20) */
  w20  = (w22*w20);
  /* #223: @20 = (@21*@20) */
  w20  = (w21*w20);
  /* #224: @30 = (@4*@30) */
  w30  = (w04*w30);
  /* #225: @30 = (@15*@30) */
  w30  = (w15*w30);
  /* #226: @20 = (@20-@30) */
  w20 -= w30;
  /* #227: output[1][15] = @20 */
  if (res[1]) res[1][15] = w20;
  /* #228: {NULL, @20, @30, @31, @32, @33} = vertsplit(@28) */
  w20 = wr28[1];
  w30 = wr28[2];
  w31 = wr28[3];
  w32 = wr28[4];
  w33 = wr28[5];
  /* #229: @34 = (@5*@31) */
  w34  = (w05*w31);
  /* #230: @35 = (@2*@33) */
  w35  = (w02*w33);
  /* #231: @30 = (@30+@35) */
  w30 += w35;
  /* #232: @36 = (@1*@30) */
  w36  = (w01*w30);
  /* #233: @36 = (@0*@36) */
  w36  = (w00*w36);
  /* #234: @34 = (@34-@36) */
  w34 -= w36;
  /* #235: @34 = (@34/@9) */
  w34 /= w09;
  /* #236: @20 = (@8*@20) */
  w20  = (w08*w20);
  /* #237: @20 = (@6*@20) */
  w20  = (w06*w20);
  /* #238: @34 = (@34+@20) */
  w34 += w20;
  /* #239: output[1][16] = @34 */
  if (res[1]) res[1][16] = w34;
  /* #240: @20 = (@1*@31) */
  w20  = (w01*w31);
  /* #241: @30 = (@5*@30) */
  w30  = (w05*w30);
  /* #242: @30 = (@0*@30) */
  w30  = (w00*w30);
  /* #243: @20 = (@20+@30) */
  w20 += w30;
  /* #244: output[1][17] = @20 */
  if (res[1]) res[1][17] = w20;
  /* #245: @20 = (@10*@31) */
  w20  = (w10*w31);
  /* #246: @20 = (@3*@20) */
  w20  = (w03*w20);
  /* #247: @33 = (@11*@33) */
  w33  = (w11*w33);
  /* #248: @20 = (@20+@33) */
  w20 += w33;
  /* #249: @34 = (@8*@34) */
  w34  = (w08*w34);
  /* #250: @20 = (@20-@34) */
  w20 -= w34;
  /* #251: output[1][18] = @20 */
  if (res[1]) res[1][18] = w20;
  /* #252: @32 = (@12*@32) */
  w32  = (w12*w32);
  /* #253: @20 = (@13*@31) */
  w20  = (w13*w31);
  /* #254: @20 = (@14*@20) */
  w20  = (w14*w20);
  /* #255: @32 = (@32-@20) */
  w32 -= w20;
  /* #256: @20 = (@16*@31) */
  w20  = (w16*w31);
  /* #257: @20 = (@0*@20) */
  w20  = (w00*w20);
  /* #258: @34 = (@17*@31) */
  w34  = (w17*w31);
  /* #259: @20 = (@20+@34) */
  w20 += w34;
  /* #260: @32 = (@32-@20) */
  w32 -= w20;
  /* #261: @31 = (@19*@31) */
  w31  = (w19*w31);
  /* #262: @31 = (@7*@31) */
  w31  = (w07*w31);
  /* #263: @31 = (@18*@31) */
  w31  = (w18*w31);
  /* #264: @32 = (@32-@31) */
  w32 -= w31;
  /* #265: @32 = (@22*@32) */
  w32  = (w22*w32);
  /* #266: @32 = (@21*@32) */
  w32  = (w21*w32);
  /* #267: @35 = (@4*@35) */
  w35  = (w04*w35);
  /* #268: @35 = (@15*@35) */
  w35  = (w15*w35);
  /* #269: @32 = (@32-@35) */
  w32 -= w35;
  /* #270: output[1][19] = @32 */
  if (res[1]) res[1][19] = w32;
  /* #271: {NULL, @32, @35, @31, @20, @34} = vertsplit(@29) */
  w32 = wr29[1];
  w35 = wr29[2];
  w31 = wr29[3];
  w20 = wr29[4];
  w34 = wr29[5];
  /* #272: @33 = (@5*@31) */
  w33  = (w05*w31);
  /* #273: @30 = (@2*@34) */
  w30  = (w02*w34);
  /* #274: @35 = (@35+@30) */
  w35 += w30;
  /* #275: @36 = (@1*@35) */
  w36  = (w01*w35);
  /* #276: @36 = (@0*@36) */
  w36  = (w00*w36);
  /* #277: @33 = (@33-@36) */
  w33 -= w36;
  /* #278: @33 = (@33/@9) */
  w33 /= w09;
  /* #279: @32 = (@8*@32) */
  w32  = (w08*w32);
  /* #280: @32 = (@6*@32) */
  w32  = (w06*w32);
  /* #281: @33 = (@33+@32) */
  w33 += w32;
  /* #282: output[1][20] = @33 */
  if (res[1]) res[1][20] = w33;
  /* #283: @32 = (@1*@31) */
  w32  = (w01*w31);
  /* #284: @35 = (@5*@35) */
  w35  = (w05*w35);
  /* #285: @35 = (@0*@35) */
  w35  = (w00*w35);
  /* #286: @32 = (@32+@35) */
  w32 += w35;
  /* #287: output[1][21] = @32 */
  if (res[1]) res[1][21] = w32;
  /* #288: @32 = (@10*@31) */
  w32  = (w10*w31);
  /* #289: @32 = (@3*@32) */
  w32  = (w03*w32);
  /* #290: @34 = (@11*@34) */
  w34  = (w11*w34);
  /* #291: @32 = (@32+@34) */
  w32 += w34;
  /* #292: @33 = (@8*@33) */
  w33  = (w08*w33);
  /* #293: @32 = (@32-@33) */
  w32 -= w33;
  /* #294: output[1][22] = @32 */
  if (res[1]) res[1][22] = w32;
  /* #295: @20 = (@12*@20) */
  w20  = (w12*w20);
  /* #296: @32 = (@13*@31) */
  w32  = (w13*w31);
  /* #297: @32 = (@14*@32) */
  w32  = (w14*w32);
  /* #298: @20 = (@20-@32) */
  w20 -= w32;
  /* #299: @32 = (@16*@31) */
  w32  = (w16*w31);
  /* #300: @32 = (@0*@32) */
  w32  = (w00*w32);
  /* #301: @33 = (@17*@31) */
  w33  = (w17*w31);
  /* #302: @32 = (@32+@33) */
  w32 += w33;
  /* #303: @20 = (@20-@32) */
  w20 -= w32;
  /* #304: @31 = (@19*@31) */
  w31  = (w19*w31);
  /* #305: @31 = (@7*@31) */
  w31  = (w07*w31);
  /* #306: @31 = (@18*@31) */
  w31  = (w18*w31);
  /* #307: @20 = (@20-@31) */
  w20 -= w31;
  /* #308: @20 = (@22*@20) */
  w20  = (w22*w20);
  /* #309: @20 = (@21*@20) */
  w20  = (w21*w20);
  /* #310: @30 = (@4*@30) */
  w30  = (w04*w30);
  /* #311: @30 = (@15*@30) */
  w30  = (w15*w30);
  /* #312: @20 = (@20-@30) */
  w20 -= w30;
  /* #313: output[1][23] = @20 */
  if (res[1]) res[1][23] = w20;
  /* #314: @37 = zeros(2x6,2nz) */
  casadi_clear(w37, 2);
  /* #315: @38 = 00 */
  /* #316: @39 = ones(2x1) */
  casadi_fill(w39, 2, 1.);
  /* #317: {@20, @30} = vertsplit(@39) */
  w20 = w39[0];
  w30 = w39[1];
  /* #318: @39 = vertcat(@38, @38, @38, @38, @20, @30) */
  rr=w39;
  *rr++ = w20;
  *rr++ = w30;
  /* #319: @40 = @39[:2] */
  for (rr=w40, cs=w39+0; cs!=w39+2; cs+=1) *rr++ = *cs;
  /* #320: (@37[:2] = @40) */
  for (rr=w37+0, cs=w40; rr!=w37+2; rr+=1) *rr = *cs++;
  /* #321: @40 = @37' */
  casadi_trans(w37,casadi_s1, w40, casadi_s0, iw);
  /* #322: @41 = project(@40) */
  casadi_project(w40, casadi_s0, w41, casadi_s2, w);
  /* #323: @42 = input[2][0] */
  wr42 = arg[2] ? arg[2] : casadi_zeros;
  /* #324: {@29, @28} = horzsplit(@42) */
  wr29 = wr42;
  wr28 = wr42+6;
  /* #325: {NULL, @20, @30, @31, @32, @33} = vertsplit(@29) */
  w20 = wr29[1];
  w30 = wr29[2];
  w31 = wr29[3];
  w32 = wr29[4];
  w33 = wr29[5];
  /* #326: @34 = (@5*@31) */
  w34  = (w05*w31);
  /* #327: @35 = (@2*@33) */
  w35  = (w02*w33);
  /* #328: @30 = (@30+@35) */
  w30 += w35;
  /* #329: @36 = (@1*@30) */
  w36  = (w01*w30);
  /* #330: @36 = (@0*@36) */
  w36  = (w00*w36);
  /* #331: @34 = (@34-@36) */
  w34 -= w36;
  /* #332: @34 = (@34/@9) */
  w34 /= w09;
  /* #333: @20 = (@8*@20) */
  w20  = (w08*w20);
  /* #334: @20 = (@6*@20) */
  w20  = (w06*w20);
  /* #335: @34 = (@34+@20) */
  w34 += w20;
  /* #336: @20 = (@1*@31) */
  w20  = (w01*w31);
  /* #337: @30 = (@5*@30) */
  w30  = (w05*w30);
  /* #338: @30 = (@0*@30) */
  w30  = (w00*w30);
  /* #339: @20 = (@20+@30) */
  w20 += w30;
  /* #340: @30 = (@10*@31) */
  w30  = (w10*w31);
  /* #341: @30 = (@3*@30) */
  w30  = (w03*w30);
  /* #342: @33 = (@11*@33) */
  w33  = (w11*w33);
  /* #343: @30 = (@30+@33) */
  w30 += w33;
  /* #344: @33 = (@8*@34) */
  w33  = (w08*w34);
  /* #345: @30 = (@30-@33) */
  w30 -= w33;
  /* #346: @32 = (@12*@32) */
  w32  = (w12*w32);
  /* #347: @33 = (@13*@31) */
  w33  = (w13*w31);
  /* #348: @33 = (@14*@33) */
  w33  = (w14*w33);
  /* #349: @32 = (@32-@33) */
  w32 -= w33;
  /* #350: @33 = (@16*@31) */
  w33  = (w16*w31);
  /* #351: @33 = (@0*@33) */
  w33  = (w00*w33);
  /* #352: @36 = (@17*@31) */
  w36  = (w17*w31);
  /* #353: @33 = (@33+@36) */
  w33 += w36;
  /* #354: @32 = (@32-@33) */
  w32 -= w33;
  /* #355: @31 = (@19*@31) */
  w31  = (w19*w31);
  /* #356: @31 = (@7*@31) */
  w31  = (w07*w31);
  /* #357: @31 = (@18*@31) */
  w31  = (w18*w31);
  /* #358: @32 = (@32-@31) */
  w32 -= w31;
  /* #359: @32 = (@22*@32) */
  w32  = (w22*w32);
  /* #360: @32 = (@21*@32) */
  w32  = (w21*w32);
  /* #361: @35 = (@4*@35) */
  w35  = (w04*w35);
  /* #362: @35 = (@15*@35) */
  w35  = (w15*w35);
  /* #363: @32 = (@32-@35) */
  w32 -= w35;
  /* #364: @43 = vertcat(@34, @20, @30, @32, @38, @38) */
  rr=w43;
  *rr++ = w34;
  *rr++ = w20;
  *rr++ = w30;
  *rr++ = w32;
  /* #365: {NULL, @34, @20, @30, @32, @35} = vertsplit(@28) */
  w34 = wr28[1];
  w20 = wr28[2];
  w30 = wr28[3];
  w32 = wr28[4];
  w35 = wr28[5];
  /* #366: @31 = (@5*@30) */
  w31  = (w05*w30);
  /* #367: @2 = (@2*@35) */
  w02 *= w35;
  /* #368: @20 = (@20+@2) */
  w20 += w02;
  /* #369: @33 = (@1*@20) */
  w33  = (w01*w20);
  /* #370: @33 = (@0*@33) */
  w33  = (w00*w33);
  /* #371: @31 = (@31-@33) */
  w31 -= w33;
  /* #372: @31 = (@31/@9) */
  w31 /= w09;
  /* #373: @34 = (@8*@34) */
  w34  = (w08*w34);
  /* #374: @6 = (@6*@34) */
  w06 *= w34;
  /* #375: @31 = (@31+@6) */
  w31 += w06;
  /* #376: @1 = (@1*@30) */
  w01 *= w30;
  /* #377: @5 = (@5*@20) */
  w05 *= w20;
  /* #378: @5 = (@0*@5) */
  w05  = (w00*w05);
  /* #379: @1 = (@1+@5) */
  w01 += w05;
  /* #380: @10 = (@10*@30) */
  w10 *= w30;
  /* #381: @3 = (@3*@10) */
  w03 *= w10;
  /* #382: @11 = (@11*@35) */
  w11 *= w35;
  /* #383: @3 = (@3+@11) */
  w03 += w11;
  /* #384: @8 = (@8*@31) */
  w08 *= w31;
  /* #385: @3 = (@3-@8) */
  w03 -= w08;
  /* #386: @12 = (@12*@32) */
  w12 *= w32;
  /* #387: @13 = (@13*@30) */
  w13 *= w30;
  /* #388: @14 = (@14*@13) */
  w14 *= w13;
  /* #389: @12 = (@12-@14) */
  w12 -= w14;
  /* #390: @16 = (@16*@30) */
  w16 *= w30;
  /* #391: @0 = (@0*@16) */
  w00 *= w16;
  /* #392: @17 = (@17*@30) */
  w17 *= w30;
  /* #393: @0 = (@0+@17) */
  w00 += w17;
  /* #394: @12 = (@12-@0) */
  w12 -= w00;
  /* #395: @19 = (@19*@30) */
  w19 *= w30;
  /* #396: @7 = (@7*@19) */
  w07 *= w19;
  /* #397: @18 = (@18*@7) */
  w18 *= w07;
  /* #398: @12 = (@12-@18) */
  w12 -= w18;
  /* #399: @22 = (@22*@12) */
  w22 *= w12;
  /* #400: @21 = (@21*@22) */
  w21 *= w22;
  /* #401: @4 = (@4*@2) */
  w04 *= w02;
  /* #402: @15 = (@15*@4) */
  w15 *= w04;
  /* #403: @21 = (@21-@15) */
  w21 -= w15;
  /* #404: @44 = vertcat(@31, @1, @3, @21, @38, @38) */
  rr=w44;
  *rr++ = w31;
  *rr++ = w01;
  *rr++ = w03;
  *rr++ = w21;
  /* #405: @45 = horzcat(@43, @44) */
  rr=w45;
  for (i=0, cs=w43; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w44; i<4; ++i) *rr++ = *cs++;
  /* #406: @46 = project(@45) */
  casadi_project(w45, casadi_s3, w46, casadi_s2, w);
  /* #407: @41 = (@41+@46) */
  for (i=0, rr=w41, cs=w46; i<10; ++i) (*rr++) += (*cs++);
  /* #408: output[2][0] = @41 */
  casadi_copy(w41, 10, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int Spatialbicycle_model_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Spatialbicycle_model_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Spatialbicycle_model_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Spatialbicycle_model_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Spatialbicycle_model_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Spatialbicycle_model_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Spatialbicycle_model_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void Spatialbicycle_model_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Spatialbicycle_model_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int Spatialbicycle_model_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real Spatialbicycle_model_expl_vde_forw_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Spatialbicycle_model_expl_vde_forw_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Spatialbicycle_model_expl_vde_forw_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Spatialbicycle_model_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    case 3: return casadi_s7;
    case 4: return casadi_s8;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Spatialbicycle_model_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s9;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Spatialbicycle_model_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 11;
  if (sz_res) *sz_res = 9;
  if (sz_iw) *sz_iw = 3;
  if (sz_w) *sz_w = 162;
  return 0;
}

CASADI_SYMBOL_EXPORT int Spatialbicycle_model_expl_vde_forw_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 11*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 9*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 3*sizeof(casadi_int);
  if (sz_w) *sz_w = 162*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
