/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) rc_car_kloeser_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[3] = {4, 1, 1};
static const casadi_int casadi_s1[3] = {2, 1, 1};
static const casadi_int casadi_s2[3] = {1, 1, 1};
static const casadi_int casadi_s3[3] = {6, 1, 1};

/* rc_car_kloeser_expl_vde_adj:(i0[4],i1[4],i2[2],i3)->(o0[6]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12;
  a00=0.;
  if (res[0]!=0) res[0][0]=a00;
  a00=arg[3]? arg[3][0] : 0;
  a01=arg[0]? arg[0][3] : 0;
  a02=arg[0]? arg[0][2] : 0;
  a03=5.0000000000000000e-01;
  a04=arg[2]? arg[2][0] : 0;
  a04=(a03*a04);
  a02=(a02+a04);
  a05=cos(a02);
  a06=(a01*a05);
  a07=1.;
  a08=arg[0]? arg[0][1] : 0;
  a08=(a08*a00);
  a07=(a07-a08);
  a06=(a06/a07);
  a06=(a06/a07);
  a08=arg[1]? arg[1][0] : 0;
  a09=arg[1]? arg[1][2] : 0;
  a10=(a00*a09);
  a08=(a08-a10);
  a06=(a06*a08);
  a00=(a00*a06);
  if (res[0]!=0) res[0][1]=a00;
  a00=arg[1]? arg[1][1] : 0;
  a06=(a01*a00);
  a06=(a05*a06);
  a02=sin(a02);
  a08=(a08/a07);
  a07=(a01*a08);
  a07=(a02*a07);
  a10=(a06-a07);
  if (res[0]!=0) res[0][2]=a10;
  a10=9.0909090909090917e+00;
  a11=sin(a04);
  a11=(a11*a09);
  a10=(a10*a11);
  a11=10.;
  a12=arg[1]? arg[1][3] : 0;
  a11=(a11*a12);
  a10=(a10-a11);
  a02=(a02*a00);
  a10=(a10+a02);
  a05=(a05*a08);
  a10=(a10+a05);
  if (res[0]!=0) res[0][3]=a10;
  a04=cos(a04);
  a10=1.1000000000000000e-01;
  a01=(a01/a10);
  a01=(a01*a09);
  a04=(a04*a01);
  a04=(a04+a06);
  a04=(a04-a07);
  a03=(a03*a04);
  if (res[0]!=0) res[0][4]=a03;
  if (res[0]!=0) res[0][5]=a11;
  return 0;
}

CASADI_SYMBOL_EXPORT int rc_car_kloeser_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int rc_car_kloeser_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int rc_car_kloeser_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void rc_car_kloeser_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int rc_car_kloeser_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void rc_car_kloeser_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void rc_car_kloeser_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void rc_car_kloeser_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int rc_car_kloeser_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int rc_car_kloeser_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real rc_car_kloeser_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* rc_car_kloeser_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* rc_car_kloeser_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* rc_car_kloeser_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* rc_car_kloeser_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int rc_car_kloeser_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int rc_car_kloeser_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
