/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Spatialbicycle_model_constr_h_fun_jac_uxt_zt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[3] = {0, 2, 5};
static const casadi_int casadi_s1[3] = {1, 3, 6};
static const casadi_int casadi_s2[3] = {6, 1, 1};
static const casadi_int casadi_s3[3] = {2, 1, 1};
static const casadi_int casadi_s4[3] = {0, 1, 1};
static const casadi_int casadi_s5[3] = {1, 1, 1};
static const casadi_int casadi_s6[3] = {5, 1, 1};
static const casadi_int casadi_s7[16] = 
  {8, 5, 0, 2, 5, 6, 7, 8,
  5, 6, 5, 6, 7, 3, 6, 7};
static const casadi_int casadi_s8[3] = {5, 0, 1};

/* Spatialbicycle_model_constr_h_fun_jac_uxt_zt:(i0[6],i1[2],i2[0],i3)->(o0[5],o1[8x5,8nz],o2[5x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, w00, w01, w02, w03, w04, w05, w06, w07, w08, w09, w10;
  casadi_real w11, w12, w13, w14, w15, w16, w17, w18, w19, *w20=w+20, *w21=w+28, *w23=w+34;
  casadi_real *w24=w+37, *w25=w+40, *w26=w+42;
  const casadi_int *cii;
  const casadi_real *cs;
  /* #0: @0 = 0.28 */
  w00 = 2.8000000000000003e-01;
  /* #1: @1 = 0.05 */
  w01 = 5.0000000000000003e-02;
  /* #2: @2 = input[0][3] */
  w02 = arg[0] ? arg[0][3] : 0;
  /* #3: @3 = (@1*@2) */
  w03  = (w01*w02);
  /* #4: @0 = (@0-@3) */
  w00 -= w03;
  /* #5: @3 = input[0][4] */
  w03 = arg[0] ? arg[0][4] : 0;
  /* #6: @4 = (@0*@3) */
  w04  = (w00*w03);
  /* #7: @5 = 0.011 */
  w05 = 1.0999999999999999e-02;
  /* #8: @6 = (@5*@2) */
  w06  = (w05*w02);
  /* #9: @7 = (@6*@2) */
  w07  = (w06*w02);
  /* #10: @4 = (@4-@7) */
  w04 -= w07;
  /* #11: @7 = 0.006 */
  w07 = 6.0000000000000001e-03;
  /* #12: @8 = 5 */
  w08 = 5.;
  /* #13: @9 = (@8*@2) */
  w09  = (w08*w02);
  /* #14: @9 = tanh(@9) */
  w09 = tanh( w09 );
  /* #15: @10 = (@7*@9) */
  w10  = (w07*w09);
  /* #16: @4 = (@4-@10) */
  w04 -= w10;
  /* #17: @10 = 1.5 */
  w10 = 1.5000000000000000e+00;
  /* #18: @11 = (@4/@10) */
  w11  = (w04/w10);
  /* #19: output[0][0] = @11 */
  if (res[0]) res[0][0] = w11;
  /* #20: @11 = 15.5 */
  w11 = 1.5500000000000000e+01;
  /* #21: @12 = (@11*@2) */
  w12  = (w11*w02);
  /* #22: @13 = (@12*@2) */
  w13  = (w12*w02);
  /* #23: @14 = input[0][5] */
  w14 = arg[0] ? arg[0][5] : 0;
  /* #24: @15 = (@13*@14) */
  w15  = (w13*w14);
  /* #25: @16 = 0.5 */
  w16 = 5.0000000000000000e-01;
  /* #26: @17 = (@16*@14) */
  w17  = (w16*w14);
  /* #27: @18 = sin(@17) */
  w18 = sin( w17 );
  /* #28: @19 = (@4*@18) */
  w19  = (w04*w18);
  /* #29: @19 = (@19/@10) */
  w19 /= w10;
  /* #30: @15 = (@15+@19) */
  w15 += w19;
  /* #31: output[0][1] = @15 */
  if (res[0]) res[0][1] = w15;
  /* #32: @15 = input[0][1] */
  w15 = arg[0] ? arg[0][1] : 0;
  /* #33: output[0][2] = @15 */
  if (res[0]) res[0][2] = w15;
  /* #34: output[0][3] = @3 */
  if (res[0]) res[0][3] = w03;
  /* #35: output[0][4] = @14 */
  if (res[0]) res[0][4] = w14;
  /* #36: @20 = zeros(8x5,8nz) */
  casadi_clear(w20, 8);
  /* #37: @15 = 0.666667 */
  w15 = 6.6666666666666663e-01;
  /* #38: @21 = ones(8x1,6nz) */
  casadi_fill(w21, 6, 1.);
  /* #39: {NULL, NULL, NULL, @19, NULL, @10, NULL, NULL} = vertsplit(@21) */
  w19 = w21[3];
  w10 = w21[5];
  /* #40: @5 = (@5*@10) */
  w05 *= w10;
  /* #41: @5 = (@2*@5) */
  w05  = (w02*w05);
  /* #42: @6 = (@6*@10) */
  w06 *= w10;
  /* #43: @5 = (@5+@6) */
  w05 += w06;
  /* #44: @5 = (-@5) */
  w05 = (- w05 );
  /* #45: @1 = (@1*@10) */
  w01 *= w10;
  /* #46: @3 = (@3*@1) */
  w03 *= w01;
  /* #47: @5 = (@5-@3) */
  w05 -= w03;
  /* #48: @3 = 1 */
  w03 = 1.;
  /* #49: @9 = sq(@9) */
  w09 = casadi_sq( w09 );
  /* #50: @3 = (@3-@9) */
  w03 -= w09;
  /* #51: @8 = (@8*@10) */
  w08 *= w10;
  /* #52: @3 = (@3*@8) */
  w03 *= w08;
  /* #53: @7 = (@7*@3) */
  w07 *= w03;
  /* #54: @5 = (@5-@7) */
  w05 -= w07;
  /* #55: @7 = (@15*@5) */
  w07  = (w15*w05);
  /* #56: @11 = (@11*@10) */
  w11 *= w10;
  /* #57: @2 = (@2*@11) */
  w02 *= w11;
  /* #58: @12 = (@12*@10) */
  w12 *= w10;
  /* #59: @2 = (@2+@12) */
  w02 += w12;
  /* #60: @14 = (@14*@2) */
  w14 *= w02;
  /* #61: @5 = (@18*@5) */
  w05  = (w18*w05);
  /* #62: @5 = (@15*@5) */
  w05  = (w15*w05);
  /* #63: @14 = (@14+@5) */
  w14 += w05;
  /* #64: @22 = 00 */
  /* #65: @23 = vertcat(@7, @14, @19, @22, @22) */
  rr=w23;
  *rr++ = w07;
  *rr++ = w14;
  *rr++ = w19;
  /* #66: @24 = @23[:3] */
  for (rr=w24, cs=w23+0; cs!=w23+3; cs+=1) *rr++ = *cs;
  /* #67: (@20[0, 2, 5] = @24) */
  for (cii=casadi_s0, rr=w20, cs=w24; cii!=casadi_s0+3; ++cii, ++cs) rr[*cii] = *cs;
  /* #68: @7 = ones(8x1,1nz) */
  w07 = 1.;
  /* #69: {NULL, NULL, NULL, NULL, NULL, NULL, @14, NULL} = vertsplit(@7) */
  w14 = w07;
  /* #70: @0 = (@0*@14) */
  w00 *= w14;
  /* #71: @7 = (@15*@0) */
  w07  = (w15*w00);
  /* #72: @18 = (@18*@0) */
  w18 *= w00;
  /* #73: @18 = (@15*@18) */
  w18  = (w15*w18);
  /* #74: @24 = vertcat(@7, @18, @22, @14, @22) */
  rr=w24;
  *rr++ = w07;
  *rr++ = w18;
  *rr++ = w14;
  /* #75: @23 = @24[:3] */
  for (rr=w23, cs=w24+0; cs!=w24+3; cs+=1) *rr++ = *cs;
  /* #76: (@20[1, 3, 6] = @23) */
  for (cii=casadi_s1, rr=w20, cs=w23; cii!=casadi_s1+3; ++cii, ++cs) rr[*cii] = *cs;
  /* #77: @7 = ones(8x1,1nz) */
  w07 = 1.;
  /* #78: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, @18} = vertsplit(@7) */
  w18 = w07;
  /* #79: @13 = (@13*@18) */
  w13 *= w18;
  /* #80: @17 = cos(@17) */
  w17 = cos( w17 );
  /* #81: @16 = (@16*@18) */
  w16 *= w18;
  /* #82: @17 = (@17*@16) */
  w17 *= w16;
  /* #83: @4 = (@4*@17) */
  w04 *= w17;
  /* #84: @15 = (@15*@4) */
  w15 *= w04;
  /* #85: @13 = (@13+@15) */
  w13 += w15;
  /* #86: @25 = vertcat(@22, @13, @22, @22, @18) */
  rr=w25;
  *rr++ = w13;
  *rr++ = w18;
  /* #87: @26 = @25[:2] */
  for (rr=w26, cs=w25+0; cs!=w25+2; cs+=1) *rr++ = *cs;
  /* #88: (@20[4:10:3] = @26) */
  for (rr=w20+4, cs=w26; rr!=w20+10; rr+=3) *rr = *cs++;
  /* #89: output[1][0] = @20 */
  casadi_copy(w20, 8, res[1]);
  return 0;
}

CASADI_SYMBOL_EXPORT int Spatialbicycle_model_constr_h_fun_jac_uxt_zt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Spatialbicycle_model_constr_h_fun_jac_uxt_zt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Spatialbicycle_model_constr_h_fun_jac_uxt_zt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Spatialbicycle_model_constr_h_fun_jac_uxt_zt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Spatialbicycle_model_constr_h_fun_jac_uxt_zt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Spatialbicycle_model_constr_h_fun_jac_uxt_zt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Spatialbicycle_model_constr_h_fun_jac_uxt_zt_incref(void) {
}

CASADI_SYMBOL_EXPORT void Spatialbicycle_model_constr_h_fun_jac_uxt_zt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Spatialbicycle_model_constr_h_fun_jac_uxt_zt_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int Spatialbicycle_model_constr_h_fun_jac_uxt_zt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real Spatialbicycle_model_constr_h_fun_jac_uxt_zt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Spatialbicycle_model_constr_h_fun_jac_uxt_zt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Spatialbicycle_model_constr_h_fun_jac_uxt_zt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Spatialbicycle_model_constr_h_fun_jac_uxt_zt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    case 1: return casadi_s3;
    case 2: return casadi_s4;
    case 3: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Spatialbicycle_model_constr_h_fun_jac_uxt_zt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s6;
    case 1: return casadi_s7;
    case 2: return casadi_s8;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Spatialbicycle_model_constr_h_fun_jac_uxt_zt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 9;
  if (sz_res) *sz_res = 11;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 44;
  return 0;
}

CASADI_SYMBOL_EXPORT int Spatialbicycle_model_constr_h_fun_jac_uxt_zt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 9*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 11*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 44*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
